version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - "xpack.security.enabled=false"
    depends_on: ['elasticsearch']
    volumes:
      - kibanaconf1:/usr/share/kibana/config
    networks:
      - esnet


volumes:
  esdata1:
  kibanaconf1:

networks:
  esnet: